process_num: 1
id: 23 # data index
epoch_num: 1
device: "cuda"

num_scales: 25000
lambda_: 0.01 # regularization coefficient
eta_: 0.005 # learning rate

num_steps: 100000
save_interval: 100
score_batch_size: 1024 # <= num_scales
patience: 5000 # early stopping rate

noise_std: 0.00 # noise parcent