process_num: 5
data_num: 5 # <= N-1
device: "cuda"

num_scales: 10000
lambda_: 0.0001 # regularization coefficient
eta_: 0.01 # learning rate

num_steps: 100000
save_interval: 100
score_batch_size: 256 # <= num_scales
patience: 10000 # early stopping rate