process_num: 1
data_num: 20 # <= N-1
device: "cuda"

num_scales: 10000
lambda_: 0.0001 # regularization coefficient
eta_: 0.001 # learning rate

num_steps: 100000
save_interval: 100
score_batch_size: 256 # <= num_scales
patience: 5000 # early stopping rate

noise_std: 0.10 # noise parcent